(()=>{'use strict';
const packs=JADEWIND_ACTIONS,keys=Object.keys(packs),images={},bg=new Image(),canvases={};let en=false,selected='idle',clock=0,last=0,paused=false,forced=null,tour=false,tourIndex=0;
const names={idle:['Reposo','Idle'],attack:['Ataque','Attack'],guard:['Guardia / parry','Guard / parry'],hurt:['Daño recibido','Hit reaction'],rest:['Descanso','Rest'],motion:['Avance y regreso','Approach and retreat'],activation:['Activación','Activation'],victory:['Victoria','Victory'],defeat:['Derrota','Defeat']};
const $=s=>document.querySelector(s),tr=(es,eng)=>en?eng:es,duration=p=>p.sequence.reduce((s,[,t])=>s+t,0);
function frame(p,age,loop=p.loop){let t=loop?Math.max(0,age)%duration(p):Math.min(Math.max(0,age),duration(p)-1);for(const[f,ms]of p.sequence){if(t<ms)return f;t-=ms}return p.sequence.at(-1)[0]}
function pose(key,t){const p=packs[key],age=t*(key==='idle'?1:Number($('#speed').value));if(key==='idle')return{key,f:frame(p,age),age};if(age<duration(p)||key==='defeat')return{key,f:frame(p,age,false),age};return{key:'idle',f:frame(packs.idle,(age-duration(p))/Number($('#speed').value)),age:0}}
function draw(ctx,key,f,x,y,height){const p=packs[key],r=p.frames[f],s=height/506*p.scale*(p.frameScale?.[f]||1);ctx.save();ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';const poly=p.clips?.[f];if(poly){ctx.beginPath();poly.forEach(([px,py],i)=>{const a=x+(px-r[0]-r[4])*s,b=y+(py-r[1]-r[5])*s;i?ctx.lineTo(a,b):ctx.moveTo(a,b)});ctx.closePath();ctx.clip()}ctx.drawImage(images[key],r[0],r[1],r[2],r[3],x-r[4]*s,y-r[5]*s,r[2]*s,r[3]*s);ctx.restore()}
function floor(ctx,w,y){ctx.strokeStyle='#597d72';ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}
function travel(t){const end=duration(packs.motion),u=Math.min(1,t/end);return u<.43?Math.sin(u/.43*Math.PI/2)*190:Math.cos((u-.43)/.57*Math.PI/2)*190}
function render(){const st=forced===null?pose(selected,clock):{key:selected,f:forced,age:0};
const dc=$('#detail').getContext('2d');dc.clearRect(0,0,700,470);floor(dc,700,400);draw(dc,st.key,st.f,350,400,360);if(st.key==='attack'&&forced===null)GuardianMeleeFX.draw(dc,{id:'jadewind',age:st.age+360,frame:st.f,pack:packs.attack,factor:360/506,x:350,y:400});
const ac=$('#arena').getContext('2d');ac.clearRect(0,0,1280,640);ac.drawImage(bg,0,0,1280,640);draw(ac,st.key,st.f,460+(st.key==='motion'&&forced===null?travel(st.age):0),450,230);if(st.key==='attack'&&forced===null)GuardianMeleeFX.draw(ac,{id:'jadewind',age:st.age+360,frame:st.f,pack:packs.attack,factor:230/506,x:460,y:450});
$('#status').textContent=names[st.key][en?1:0]+' · '+(st.f+1)+'/'+packs[st.key].frames.length;
for(const key of keys){const c=canvases[key],ctx=c.getContext('2d'),p=packs[key],cycle=key==='idle'?clock:clock%((duration(p)/Number($('#speed').value))+1800),q=pose(key,cycle);ctx.clearRect(0,0,c.width,c.height);floor(ctx,c.width,250);draw(ctx,q.key,q.f,220,250,220)}
return st}
function contact(){const host=$('#contact');host.replaceChildren();const p=packs[selected];for(let i=0;i<p.frames.length;i++){const b=document.createElement('button'),c=document.createElement('canvas');c.width=440;c.height=300;b.append(c,document.createTextNode(''+(i+1)));b.title=tr('Fotograma ','Frame ')+(i+1);floor(c.getContext('2d'),440,250);draw(c.getContext('2d'),selected,i,220,250,220);b.onclick=()=>{paused=true;tour=false;forced=i;labels();render()};host.append(b)}}
function select(key){selected=key;clock=0;forced=null;paused=false;contact();labels();render()}
function labels(){document.documentElement.lang=en?'en':'es';$('#title').textContent=tr('Viento de Jade · Todas las animaciones','Jade Wind · All animations');$('#intro').textContent=tr('9 acciones · Idle aprobado a 1× · Resto a 1.5× · La habilidad depende del equipo, no de la apariencia.','9 actions · Approved idle at 1× · Other actions at 1.5× · Skills depend on equipment, not appearance.');$('#lang').textContent=en?'Español':'English';$('#pause').textContent=paused?tr('Continuar','Resume'):tr('Pausar','Pause');$('#restart').textContent=tr('Repetir acción','Replay action');$('#tour').textContent=tr('Ver secuencia completa','Play all actions');$('#speedLabel').textContent=tr('Acciones:','Actions:');$('#detailTitle').textContent=tr('Detalle','Detail');$('#sceneTitle').textContent=tr('Escala de combate','Battle scale');$('#inspectTitle').textContent=tr('Inspeccionar fotogramas','Inspect frames');for(const b of document.querySelectorAll('[data-key]')){b.textContent=names[b.dataset.key][en?1:0];b.setAttribute('aria-pressed',b.dataset.key===selected)}$('#footer').innerHTML=tr('Vista de animaciones; las reglas y sonidos se prueban en el combate. ','Animation preview; test rules and sounds in battle. ')+'<a href="/characters/concepts/jadewind-v1/base-v1.png">'+tr('Diseño aprobado','Approved design')+'</a> · <a href="/guardian-duel/assets/jadewind-v1/prompts.json">Prompts · image_gen</a> · <a href="/guardian-duel/?hero=jadewind">'+tr('Probar combate','Try battle')+'</a>'}
$('#lang').onclick=()=>{en=!en;labels()};$('#pause').onclick=()=>{paused=!paused;forced=null;labels()};$('#restart').onclick=()=>{tour=false;select(selected)};$('#tour').onclick=()=>{tour=true;tourIndex=0;select(keys[0])};$('#speed').onchange=()=>{clock=0;forced=null};
for(const key of keys){const b=document.createElement('button');b.dataset.key=key;b.onclick=()=>{tour=false;select(key)};$('.actions').append(b);const a=document.createElement('article'),h=document.createElement('button'),c=document.createElement('canvas');h.dataset.key=key;h.onclick=()=>{tour=false;select(key)};c.width=440;c.height=290;canvases[key]=c;a.append(h,c);$('.gallery').append(a)}labels();
function load(im,src){return new Promise((resolve,reject)=>{im.onload=resolve;im.onerror=()=>reject(new Error('Image failed: '+src));im.src=src})}
Promise.all([...keys.map(key=>{images[key]=new Image();return load(images[key],packs[key].src)}),load(bg,'/assets/demo-battle/black-lotus-arena.png')]).then(()=>{
window.jadewindPreview={ready:true,packs,keys,duration,frame,pose,draw,select,setTime(t){clock=t;paused=true;forced=null;return render()},setFrame(key,f){select(key);paused=true;forced=f;return render()},play(){paused=false;forced=null;last=0},state(){return{selected,clock,paused,pose:forced===null?pose(selected,clock):{key:selected,f:forced}}}};
const requested=location.hash.slice(1);if(keys.includes(requested))select(requested);
contact();function tick(t){if(last&&!paused&&!document.hidden)clock+=Math.min(80,t-last);last=t;if(tour&&clock>(selected==='idle'?5800:duration(packs[selected])/Number($('#speed').value)+(selected==='defeat'?2200:750))){tourIndex++;if(tourIndex<keys.length)select(keys[tourIndex]);else{tour=false;paused=true;labels()}}render();requestAnimationFrame(tick)}requestAnimationFrame(tick);
}).catch(e=>{$('#status').textContent=e.message;console.error(e)});
})();
