/* Non-browser regression harness: real client script, fake DOM/canvas, real asset paths. */
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),R=require('./rules.js'),pack=require('./lancer.js');
const dimensions=file=>{const b=fs.readFileSync(file);assert.equal(b.toString('ascii',1,4),'PNG');return [b.readUInt32BE(16),b.readUInt32BE(20)]};
for(const p of Object.values(pack)){const [w,h]=dimensions(path.join(root,p.src));for(const [x,y,cw,ch] of p.frames)assert(x>=0&&y>=0&&x+cw<=w&&y+ch<=h);for(const [f,ms] of p.sequence)assert(p.frames[f]&&ms>0)}
assert.throws(()=>new R.Battle().resolve('SPECIAL'),/unsupported/);
for(let seed=1;seed<60;seed++){let n=seed;const rng=()=>((n=(n*1664525+1013904223)>>>0)/4294967296);const b=new R.Battle(rng);for(let t=0;t<100;t++){const before=b.snapshot(),r=b.resolve(['ATTACK','DEFEND','REST'][t%3]);for(const a of r.state.actors)assert(a.hp>=0&&a.hp<=a.max);assert.deepEqual(before.actors.map(a=>a.max),r.state.actors.map(a=>a.max));if(r.finished)break;if(t===99)throw Error('battle failed to terminate');}}
let drawCalls=0;
const paint={addColorStop(){}};
const ctx=new Proxy({drawImage(im,...args){assert(im&&im.width>0);assert(args.every(Number.isFinite));if(args.length===8){const [x,y,w,h]=args;assert(x>=0&&y>=0&&x+w<=im.width&&y+h<=im.height)}drawCalls++;},createRadialGradient(){return paint}}, {get:(t,k)=>k in t?t[k]:()=>{}});
class El{constructor(id){this.id=id;this.dataset={};this.hidden=['battle','outcome','replay'].includes(id);this.disabled=false;this.children=[];this.clientWidth=390;this.clientHeight=690;this.checked=false;this.textContent='';}getContext(){return ctx}setAttribute(){}append(el){this.children.push(el)}replaceChildren(){this.children=[]}focus(){}scrollIntoView(){}get firstElementChild(){return {remove:()=>this.children.shift()}}}
const ids=[...fs.readFileSync(path.join(__dirname,'index.html'),'utf8').matchAll(/id="([^"]+)"/g)].map(m=>m[1]);
const els=Object.fromEntries(ids.map(id=>[id,new El(id)]));const actions=['ATTACK','DEFEND','REST'].map(a=>{const e=new El(a);e.dataset.action=a;return e});
let raf,time=0;const context={console,GuardianRules:R,Math,URL,URLSearchParams,location:{search:'',href:'http://localhost/guardian-duel/'},history:{replaceState(){}},matchMedia:()=>({matches:false}),document:{hidden:false,documentElement:{lang:'es'},getElementById:id=>{assert(els[id],id);return els[id]},querySelectorAll:s=>s==='[data-action]'?actions:[],createElement:()=>new El(),addEventListener(){}},Image:class{set src(v){const [w,h]=dimensions(path.join(root,v));this.width=w;this.height=h;queueMicrotask(()=>this.onload())}},Audio:class{play(){return Promise.resolve()}pause(){}},requestAnimationFrame:fn=>{raf=fn}};
vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(__dirname,'lancer.js'),'utf8'),context);vm.runInContext(fs.readFileSync(path.join(__dirname,'game.js'),'utf8'),context);
const tick=()=>{time+=50;raf(time)};
(async()=>{await new Promise(r=>setImmediate(r));await els.lancer.onclick();assert.equal(els.battle.hidden,false);for(let trial=0;trial<8;trial++){let rounds=0;while(els.replay.hidden&&rounds++<70){actions[trial%2===0?rounds%3:0].onclick();assert.equal(els.confirm.disabled,false);els.confirm.onclick();assert.equal(actions[0].disabled,true);for(let i=0;actions[0].disabled&&els.replay.hidden&&i<500;i++)tick();assert(!actions[0].disabled||!els.replay.hidden);}assert(!els.replay.hidden,'expected completed battle');assert.equal(els.outcome.hidden,false);els.replay.onclick();assert.equal(els.outcome.hidden,true);assert.equal(els['hero-hp'].value,260);}els.pause.onclick();assert.equal(els.status.textContent,'En pausa');els.pause.onclick();els.language.onclick();assert.equal(context.document.documentElement.lang,'en');els.change.onclick();assert.equal(els.selection.hidden,false);assert.equal(els.battle.hidden,true);assert(drawCalls>100);console.log('PASS: 9 atlases, 59 seeded battles, 8 animated client battles, replay, selection, pause, language, mobile canvas and crop bounds. Draw calls:',drawCalls)})().catch(e=>{console.error(e);process.exitCode=1});
